// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yqhqpmlrzgscsqrbohds.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlxaHFwbWxyemdzY3NxcmJvaGRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNDY5NDcsImV4cCI6MjA2MTcyMjk0N30.rOS9Ntiqi3rirYteNdp0Xx5vVhCgfbHWQpI-_c_Cplc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);